name: Daily update (single league)

on:
  workflow_dispatch:
    inputs:
      collection_name:
        description: 'Collection name to drop results'
        required: true
      table_url:
        description: "Url to league's table"
        required: true

env:
  ACTIONS_ALLOW_UNSECURE_COMMANDS: true

jobs:
  scrape-latest:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        
      - name: Setup Python
        uses: actions/setup-python@v4.5.0
        with:
          python-version: '3.10'
          
      - name: Install requirements
        run: pip install -r requirements.txt
        
      - name: Install playwright 
        run: playwright install

      - name: Run Scraper
        run: |
          COLLECTION_NAME=${{ github.event.inputs.collection_name }} 
          TABLE_URL=${{ github.event.inputs.table_url }} 
          python tasks/scheduled_tasks/get_teams_latest.py
        env:
          MONGO_URI:  ${{secrets.MONGO_URI}}
          MONGODB_NAME: ${{secrets.MONGODB_NAME}}
